{"timestamp":"2025-07-12T01:14:15.731184","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-12T01:14:15.731996","level":"info","event":"Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-12T01:14:15.874260Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:15.874414Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:15.874501Z","level":"info","event":"Current task name:transform_load_weather_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:15.874572Z","level":"info","event":"Dag name:weathermap_api","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:15.874640","level":"info","event":"Connection Retrieved 'aws_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-12T01:14:17.184617","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"PermissionError","exc_value":"Access Denied","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/ubuntu/airflow/dags/weather_dag.py","lineno":58,"name":"transform_load_data"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py","lineno":333,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3986,"name":"to_csv"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1014,"name":"to_csv"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":251,"name":"save"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py","lineno":157,"name":"__exit__"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py","lineno":144,"name":"close"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py","lineno":2206,"name":"close"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py","lineno":2069,"name":"flush"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":2449,"name":"_upload_chunk"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":2474,"name":"commit"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":2309,"name":"_call_s3"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py","lineno":118,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py","lineno":103,"name":"sync"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py","lineno":56,"name":"_runner"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":371,"name":"_call_s3"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":146,"name":"_error_wrapper"}],"is_group":false,"exceptions":[]},{"exc_type":"ClientError","exc_value":"An error occurred (AccessDenied) when calling the PutObject operation: Access Denied","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3fs/core.py","lineno":114,"name":"_error_wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/context.py","lineno":36,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/aiobotocore/client.py","lineno":415,"name":"_make_api_call"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-12T01:14:17.186051Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:17.186152Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:17.186205Z","level":"info","event":"Task:<Task(PythonOperator): transform_load_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-12T01:14:17.186250Z","level":"info","event":"Failure caused by Access Denied","chan":"stdout","logger":"task"}
